---
- name: "Install apt-keys by URL"
  apt_key:
    url: "{{ item.key.url }}"
  loop: "{{ apt_packages.from_url | default([]) }}"
  loop_control:
    label: "'{{ item.name }}'"

- name: "Install apt-keys by ID from a keyserver"
  apt_key:
    id: "{{ item.key.id }}"
    keyserver: "{{ item.key.keyserver }}"
  loop: "{{ apt_packages.from_keyserver | default([]) }}"
  loop_control:
    label: "'{{ item.name }}'"

- name: "Add all repos"
  apt_repository:
    repo: "{{ item.repo.url }} {{ item.repo.codename | default(default_codename) }} {{ item.repo.components }}"
    filename: "{{ item.name | lower | replace(' ', '-')}}"
    update_cache: no
  loop: "{{ apt_packages.from_url + apt_packages.from_keyserver }}"
  loop_control:
    label: "'{{ item.name }}'"

- name: "Update apt cache"
  apt:
    update_cache: yes

- name: "Install all of the packages"
  apt:
    name: "{{ item.package }}"
  loop: "{{ apt_packages.from_url + apt_packages.from_keyserver }}"
  loop_control:
    label: "'{{ item.package }}'"

- name: "Install packages that have to downloaded with wget"
  include: wget_deb_and_install.yml
  loop: "{{ apt_packages.with_wget | default([]) }}"
  loop_control:
    label: "'{{ item.package }}'"
